[package]
name = "network_analysis_utility"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = "1.47.2"
reqwest = "0.12.24"
serde = "1.0.228"
serde_json = "1.0.145"
hyper = "1.8.1"
pnet = "0.35.0"
pnet_datalink = "0.35.0"
dns-lookup = "3.0.1"